version: '3.8'

services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    restart: unless-stopped
    environment:
      - QUEUE_HOST=redis
      - QUEUE_PORT=6379
      - MONGO_URI=mongodb://mongo:27017/nest
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run start:dev

  redis:
    image: redis:6.2.6
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'

  mongo:
    image: mongo:4.4.29
    container_name: mongo
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
